language: python
python:
  - "3.7"
install:
  - pip install .
  - pip install flake8 pylint coveralls cryptography
script:
- flake8 adb_shell/ && pylint adb_shell/ && coverage run --source adb_shell setup.py test && coverage report -m
after_success:
- coveralls
